import { StyleSheet } from 'react-native'

export default styles = StyleSheet.create({
  mainFormWrap: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  customTop: {
    top: 7,
    right: 30,
    width: 100,
  },
  maiinDetailBtn: {
    flexDirection: 'row',
  },
  unitDetailInput: {
    width: '70%',
  },
  mainDetailViewBtn: {
    width: '30%',
    paddingLeft: 15,
  },
  unitDetailBtn: {
    borderWidth: 1,
    borderColor: '#016FF2',
    height: 48,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  detailBtnText: {
    textAlign: 'center',
    color: '#016FF2',
  },
  removePad: {
    paddingTop: 0,
  },
  addMoreBtnMain: {
    flexDirection: 'row'
  },
  backgroundBlue: {
    backgroundColor: '#0070f1',
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 11,
    paddingTop: 11,
    borderRadius: 4,
    position: 'relative',
  },
  priceValue: {
    color: '#fff',
    fontSize: 18,
    marginTop: 0,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  finalPrice: {
    marginBottom: 2,
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  sidePriceFormat: {
    position: 'absolute',
    right: 20,
    bottom: 12,
    color: '#fff',
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  bookNowBtn: {
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#006ff1',
    backgroundColor: '#fff',
  },
  bookNowBtnText: {
    color: '#006ff1',
    fontWeight: 'bold',
    letterSpacing: 2,
    paddingTop: 18,
    paddingBottom: 18,
    textAlign: 'center',
    fontSize: 18,
  },
  // Second Screen Styling
  bookedBtnText: {
    backgroundColor: '#006ff1',
    color: '#fff',
    textAlign: 'center',
    paddingTop: 15,
    paddingBottom: 15,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 2,
    borderRadius: 4,
    marginBottom: 15,
  },
  bookedBtnImage: {
    resizeMode: 'contain',
    width: 20,
    marginRight: 10,
    height: 19,
  },
  firstContainer: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  mainTopDetailsWrap: {
    backgroundColor: '#fff',
    borderRadius: 4,
    padding: 10,
    marginBottom: 15,
  },
  detailsRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  leftDetailsText: {
    fontSize: 16,
    flex: 1,
    color: '#000',
  },
  rightDetailsText: {
    fontSize: 16,
    flex: 1,
    color: '#006ff1',
    fontWeight: 'bold',
  },
  paymentsHeading: {
    backgroundColor: '#006ff1',
    color: '#fff',
    paddingTop: 15,
    paddingBottom: 15,
    fontSize: 17,
    paddingLeft: 10,
  },
  mainPaymentWrap: {
    backgroundColor: '#fff',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  addPaymentBtn: {
    flexDirection: 'row',
    borderColor: '#006ff1',
    borderRadius: 4,
    borderWidth: 1,
    color: '#006ff1',
    textAlign: 'center',
    paddingTop: 15,
    paddingBottom: 15,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 2,
    borderRadius: 4,
    marginBottom: 15,
    justifyContent: 'center',
    marginTop: 15,
  },
  addPaymentBtnImg: {
    resizeMode: 'contain',
    width: 20,
    marginRight: 10,
    height: 19,
  },
  addPaymentBtnText: {
    color: '#006ff1',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  scrollHeight: {
    height: 205,
  },
});