/** @format */

import { StyleSheet, Platform } from 'react-native'
import AppStyles from '../../AppStyles'
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen'

export default styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: AppStyles.colors.primaryColor,
    paddingHorizontal: wp('0%'),
    paddingLeft: 0,
  },
  scrollContainer: {
    paddingVertical: 15,
  },
  buttonWrap: {
    marginBottom: 50,
  },
  mainbutton: {
    borderWidth: 1,
    borderColor: '#696969',
    alignItems: 'center',
    minHeight: 150,
    borderRadius: 5,
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 28,
  },
  containerImg: {
    margin: 5,
    width: 12,
    height: 12,
    resizeMode: 'contain',
  },
  statsIcon: {
    marginRight: -15,
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  btnStyle: {
    zIndex: 10,
    borderColor: '#ffffff',
    marginHorizontal: 5,
    flexDirection: 'row',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    padding: 6,
    paddingHorizontal: 15,
    shadowColor: '#000',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.48,
    shadowRadius: 11.95,
    elevation: 18,
  },
  font: {
    fontFamily: AppStyles.fonts.boldFont,
    marginRight: 5,
  },
  btnView: {
    position: 'absolute',
    bottom: 30,
    right: 0,
    flexDirection: 'row',
    marginHorizontal: 5,
  },
  kpiContainer: {
    backgroundColor: 'white',
    minWidth: wp('45%'),
    position: 'absolute',
    height: Platform.OS === 'android' ? hp('20%') : hp('18%'),
    bottom: hp('15%'),
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    padding: 10,
    left: 0,
    shadowColor: '#000',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.48,
    shadowRadius: 11.95,
    elevation: 18,
  },
  kpiContainerFalse: {
    backgroundColor: 'white',
    minWidth: wp('5%'),
    position: 'absolute',
    minHeight: hp('18%'),
    bottom: hp('15%'),
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    padding: 10,
    left: 0,
    shadowColor: '#000',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.48,
    shadowRadius: 11.95,
    elevation: 18,
  },
  kpiText: {
    fontSize: AppStyles.fontSize.medium,
    fontFamily: AppStyles.fonts.boldFont,
  },
  trueStatsIcon: {
    zIndex: 20,
    marginRight: -30,
    width: 50,
    height: 50,
    elevation: 10,
    shadowOffset: { width: 5, height: 5 },
    shadowColor: 'lightgrey',
    shadowOpacity: 0.2,
  },
  falseStatsIcon: {
    position: 'absolute',
    minHeight: hp('15%'),
    bottom: Platform.OS === 'android' ? hp('13%') : hp('12%'),
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    padding: 10,
    left: -6,
    zIndex: 10,
  },
  loaderView: {
    justifyContent: 'center',
    alignSelf: 'center',
  },
  buttonShadowView: {
    elevation: 10,
    shadowOffset: { width: 5, height: 5 },
    shadowColor: 'lightgrey',
    shadowOpacity: 0.2,
    position: 'absolute',
    right: -5,
    top: '50%',
  },
})
