/** @format */

export const SET_LEAD = 'SET_LEAD'
export const SET_SALE = 'SET_SALE'
export const REMOVE_LEAD = 'REMOVE_LEAD'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const REMOVE_USER_ERROR = 'REMOVE_USER_ERROR'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS'
export const SET_TOKEN_ERROR = 'SET_TOKEN_ERROR'
export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_LISTING_COUNT = 'UPDATE_LISTING_COUNT'
export const GET_AREAS = 'GET_AREAS'
export const CLEAR_AREAS = 'CLEAR_AREAS'
export const SET_AREA_LOADER = 'SET_AREA_LOADER'
export const SET_SELECTED_AREAS = 'SET_SELECTED_AREAS'
export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS'
export const IMAGE_UPLOAD_ERROR = 'IMAGE_UPLOAD_ERROR'
export const IMAGE_REMOVE = 'IMAGE_REMOVE'
export const ADD_IMAGES = 'ADD_IMAGES'
export const FLUSH_IMAGES = ' FLUSH_IMAGES'
export const SET_IMAGE_LOADING = 'SET_IMAGE_LOADING'
export const SET_CONTACTS = 'SET_CONTACTS'
export const SET_INTERNET_CONNECTION = 'SET_INTERNET_CONNECTION'
export const SET_CM_PAYMENT = 'SET_CM_PAYMENT'
export const SET_RCM_PAYMENT = 'SET_RCM_PAYMENT'
export const SET_UPDATE_LOADER = 'SET_UPDATE_LOADER'
export const SET_PROPSURE_PAYMENT = 'SET_PROPSURE_PAYMENT'
export const SET_CM_TAX = 'SET_CM_TAX'
export const SET_LEGAL_PAYMENT = 'SET_LEGAL_PAYMENT'
export const SET_PP_BUY_NOTIFICATION = 'SET_PP_BUY_NOTIFICATION'
export const SET_INSTRUMENT_INFORMATION = 'SET_INSTRUMENT_INFORMATION'
export const CLEAR_INSTRUMENT_INFORMATION = 'CLEAR_INSTRUMENT_INFORMATION'
export const CLEAR_INSTRUMENTS_LIST = 'CLEAR_INSTRUMENTS_LIST'
export const SET_INSTRUMENTS = 'SET_INSTRUMENTS'
export const SET_CALL_PAYLOAD = 'SET_CALL_PAYLOAD'
export const SEND_CALL_STATUS = 'SEND_CALL_STATUS'
export const SET_CALL_COMMENT = 'SET_CALL_COMMENT'
export const CLEAR_CALL_PAYLOAD = 'CLEAR_CALL_PAYLOAD'

export const SET_SLOT_DIARY_DATA = 'SET_SLOT_DIARY_DATA' // ARMS-2180
export const SET_TIME_SLOTS = 'SET_TIME_SLOTS' // ARMS-2180
export const SET_SLOTS_PAYLOAD = 'SET_SLOTS_PAYLOAD' // ARMS-2180
export const SET_SCHEDULED_TASKS = 'SET_SCHEDULED_TASKS' // ARMS-2180
export const CLEAR_SLOT_DIARY_DATA = 'CLEAR_SLOT_DIARY_DATA' // ARMS-2180
export const SET_TIME_SHIFT = 'SET_TIME_SHIFT' // ARMS-2180
export const SET_SLOTS_DATA_PAYLOAD = 'SET_SLOTS_DATA_PAYLOAD' // ARMS-2180
export const ALL_TIME_SLOTS = 'ALL_TIME_SLOTS' // ARMS-2180
export const CLEAR_SLOT_DATA_DIARY = 'CLEAR_SLOT_DATA_DIARY' // ARMS-2180
export const CLEAR_SCHEDULED_TASKS = 'CLEAR_SCHEDULED_TASKS' // ARMS-2180

export const GET_DIARY_STATS = 'GET_DIARY_STATS' // ARMS-2448

export const GET_DIARIES = 'GET_DIARIES'
export const CLEAR_DIARIES = 'CLEAR_DIARIES'
export const SET_DIARY_LOADER = 'SET_DIARY_LOADER'
export const SET_DIARY_OVERDUE_COUNT = 'SET_DIARY_OVERDUE_COUNT'
export const SET_SELECTED_DIARY = 'SET_SELECTED_DIARY'
export const SET_SELECTED_LEAD = 'SET_SELECTED_LEAD'
export const SET_CLASSIFICATION_MODAL = 'SET_CLASSIFICATION_MODAL'
export const SET_DIARY_TASK_DONE = 'SET_DIARY_TASK_DONE'
export const SET_DIARY_FILTER = 'SET_DIARY_FILTER'
export const CLEAR_DIARY_FILTER = 'CLEAR_DIARY_FILTER'
export const SET_DAIRY_FILTER_APPLIED = 'SET_DAIRY_FILTER_APPLIED'
export const SET_DIARY_PAGE_COUNT = 'SET_DIARY_PAGE_COUNT'
export const SET_DIARY_ON_END_REACHED_LOADER = 'SET_DIARY_ON_END_REACHED_LOADER'
export const SET_ADD_PROPERTY_PARAMS = 'SET_ADD_PROPERTY_PARAMS'
export const SET_PERMISSIONS = 'SET_PERMISSIONS'
export const SET_DIARY_SORT = 'SET_DIARY_SORT'
export const SET_DIARY_SELECTED_DATE = 'SET_DIARY_SELECTED_DATE'
export const SET_DIARY_AGENT_ID = 'SET_DIARY_AGENT_ID'
export const SET_DIARY_ISOVERDUE = 'SET_DIARY_ISOVERDUE'
export const SET_DIARY_FILTER_REASON = 'SET_DIARY_FILTER_REASON'
export const SET_DIARY_FEEDBACKS = 'SET_DIARY_FEEDBACKS'
export const CLEAR_DIARY_FEEDBACKS = 'CLEAR_DIARY_FEEDBACKS'
export const SET_MULTIPLE_PHONE_MODAL_VISIBLE = 'SET_MULTIPLE_PHONE_MODAL_VISIBLE'
export const SET_REFERENCE_GUIDE_DATA = 'SET_REFERENCE_GUIDE_LOADING'
//CONNECT TYPES

export const SET_CONNECT_FEEDBACK = 'SET_CONNECT_FEEDBACK'

// ARMS CONTACTS
export const GET_ARMS_CONTACTS = 'GET_ARMS_CONTACTS'
export const SET_ARMS_CONTACTS_LOADER = 'SET_ARMS_CONTACTS_LOADER'
export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT'

// DRAWER
export const SET_DRAWER_INTERNAL_MENU = 'SET_DRAWER_INTERNAL_MENU'

//ARMS-3570
export const SET_IS_TERMINAL_USER = 'SET_IS_TERMINAL_USER'

export const ADD_EDIT_CM_LEAD = 'ADD_EDIT_CM_LEAD'
export const GET_ALL_INVESTMENT_PROJECTS = 'GET_ALL_INVESTMENT_PROJECTS'
export const SET_CM_LEAD_LOADER = 'SET_CM_LEAD_LOADER'
export const SET_DEFAULT_CM_PAYLOAD = 'SET_DEFAULT_CM_PAYLOAD'
